# Meta data
name:         Ratchet
authors:      Connor Sears
description:  Build mobile apps with simple HTML, CSS, and JS components.

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
host:         0.0.0.0
port:         4000
